
#Configuration initiale 
GRID_SIZE=30
INITIAL_SHEEP=50
INITIAL_WOLVES=10
INITIAL_GRASS_COVERAGE=0.3 #30% de la grille

#Energie 
SHEEP_INITIAL_ENERGY=20
WOLF_INITIAL_ENERGY=40
SHEEP_ENERGY_FROM_GRASS=15
WOLF_ENERGY_FROM_SHEEP=35
SHEEP_ENERGY_LOSS_PER_TURN=1
WOLF_ENERGY_LOSS_PER_TURN=2 #les loups perd

#reproduction
SHEEP_REPRODUCTION_THRESHOLD=50
WOLF_REPRODUCTION_THRESHOLD=80
REPRODUCTION_ENERGY_COST=20

#Age 
SHEEP_MAX_AGE= 50
WOLF_MAX_AGE=40

#Herbe 
GRASS_GROWHT_PROBABILITY=0.08
GRASS_REGROWTH_TIME=7

#Simulation
MAX_TURN=500


class mouton :
    """
    Stocker ses cordonnées, son niveau d'énergie, son age

    se deplace aléatoirement

    se reproduit seul

    """